name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  job_build:
    name: Compilation for NanoS, X, S+, and Stax

    strategy:
      matrix:
        include:
          - model: nanos
            SDK: "$NANOS_SDK"
          - model: nanox
            SDK: "$NANOX_SDK"
          - model: nanosp
            SDK: "$NANOSP_SDK"

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make DEBUG=0 COIN=avian BOLOS_SDK=${{ matrix.SDK }} && mv bin/ avian-bin/
          make clean
          make DEBUG=0 COIN=avian_testnet && mv bin/ avian-testnet-bin/
      - name: Upload Avian app binary
        uses: actions/upload-artifact@v2
        with:
          name: avian-app-${{ matrix.model }}
          path: avian-bin

      - name: Upload Avian Testnet app binary
        uses: actions/upload-artifact@v2
        with:
          name: avian-testnet-app-${{ matrix.model }}
          path: avian-testnet-bin
